general {
    lock_cmd = pidof hyprlock || hyprlock >> /tmp/hyprlock.log
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 30
    on-timeout = $HOME/.local/bin/backlightctl save && $HOME/.local/bin/backlightctl 1
    on-resume = $HOME/.local/bin/backlightctl restore
}

listener {
    timeout = 60
    on-timeout = loginctl lock-session
}

listener {
    timeout = 120
    on-timeout = systemctl suspend
}
