source=$XDG_CONFIG_HOME/hypr/hyprland.d/outputs.conf
source=$XDG_CONFIG_HOME/hypr/hyprland.d/workspaces.conf
source=$XDG_CONFIG_HOME/hypr/hyprland.d/inputs.conf
source=$XDG_CONFIG_HOME/hypr/hyprland.d/prettify.conf
source=$XDG_CONFIG_HOME/hypr/hyprland.d/windowrules.conf
source=$XDG_CONFIG_HOME/hypr/hyprland.d/general-keybinds.conf
source=$XDG_CONFIG_HOME/hypr/hyprland.d/hyprland-keybinds.conf
source=$XDG_CONFIG_HOME/hypr/hyprland.d/autostart.conf
source=$XDG_CONFIG_HOME/hypr/hyprland.d/envvars.conf

debug {
    disable_logs=false
  }
