# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'rickstaa/tmux-notify'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# change prefix to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf
bind c new-window -c "#{pane_current_path}"

set -g mouse on
set -s copy-command 'wl-copy'

set-option -g status-position bottom

bind-key -n C-Pageup prev
bind-key -n C-Pagedown next

setw -g mode-keys vi
set-option -g status-keys vi		# Use Vi bindings in tmux command prompt.
set-window-option -g mode-keys vi	# Use Vi bindings in copy and choice mode.

# Optional: some Vi-like navigation for smart pane switching.
# NOTE this could override default keybindings like <prefix>-l.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi C-c send-keys -X copy-pipe-and-cancel

bind P paste-buffer
# bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel
unbind-key -T copy-mode-vi MouseDragEnd1Pane

# Move windows
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# image.nvim
set -gq allow-passthrough on
set -g visual-activity off

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
