exec-once=ags run
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=hyprpaper >> /tmp/hyprpaper.log
exec-once=hypridle >> /tmp/hypridle.log
exec-once=sleep 5s && ibus-daemon -dxvR
exec-once=kdeconnect-indicator
exec-once=sleep 5s && Telegram -startintray
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=hyprpm reload -n
exec-once=$HOME/.local/bin/waydroid-sm restart
exec-once=easyeffects --gapplication-service
exec-once=/usr/bin/steam-native -silent
