# App Keybindings
bind=SUPER,return,exec,alacritty -e tmux
bind=SUPERSHIFT,return,exec,alacritty -e tmux attach
bind=SUPER,C,exec,wl-color-picker clipboard
bind=SUPER,D,exec,wofi --show drun,run --allow-images
bind=SUPER,period,exec,wofimoji --action type

# Whole screen
bind=,PRINT,exec,$HOME/.local/bin/wl-capture whole
bind=SHIFT,PRINT,exec,$HOME/.local/bin/wl-capture whole --copy
bind=CTRL,PRINT,exec,$HOME/.local/bin/wl-capture whole --edit

# Active monitor
bind=ALT,PRINT,exec,$HOME/.local/bin/wl-capture active-mon
bind=ALTSHIFT,PRINT,exec,$HOME/.local/bin/wl-capture active-mon --copy
bind=ALTCTRL,PRINT,exec,$HOME/.local/bin/wl-capture active-mon --edit

# Selected area
bind=SUPER,S,exec,$HOME/.local/bin/wl-capture part
bind=SUPERSHIFT,S,exec,$HOME/.local/bin/wl-capture part --copy
bind=SUPERCTRL,S,exec,$HOME/.local/bin/wl-capture part --edit

# Firefox
bind=SUPER,F,exec,firefox-developer-edition
bind=CONTROLSUPER,F,exec,firefox-developer-edition --ProfileManager
bind=SUPERALT,F,exec,firefox-developer-edition --private-window

# Zen
bind=SUPER,Z,exec,zen-browser

# bind=SUPERALT,S,exec,sleep 1s && ~/.local/bin/saver.sh
bind=SUPER,V,exec,code
bind=SUPER,E,exec,epiphany --profile $HOME/.local/share/epiphany/default
bind=SUPERSHIFT,E,exec,epiphany --profile $HOME/.local/share/epiphany/work
bind=SUPERSHIFT,T,exec,Telegram
bind=SUPERSHIFT,C,exec,chromium --enable-features=UseOzonePlatform --ozone-platform=wayland
bind=SUPERSHIFT,F,exec,firefox
bind=SUPERSHIFT,D,exec,systemd-run --user --scope -p MemoryLimit=1024M vesktop
bind=SUPER,XF86Favorites,exec,firefox -P testing
bind=SUPERSHIFT,P,exec,pwvucontrol
bind=SUPERSHIFT, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
bind=SUPERALTSHIFT,F,exec,firefox-developer-edition --ProfileManager
bind=SUPERALTSHIFT,P,exec,systemctl poweroff
bind=SUPERALTSHIFT,R,exec,systemctl reboot
bind=SUPERALTSHIFT,S,exec,systemctl suspend
bind=CONTROLALT,F,exec,thunar
bind=CONTROLSHIFT,Escape,exec,alacritty -e btop
bind=SUPERALTSHIFT,Backspace,exit
bind=SUPERSHIFT,Z,plugin:dynamic-cursors:magnify, 500, 5

# Media Keybindings
bind=,xf86audiolowervolume,exec,wpctl set-volume @DEFAULT_SINK@ 2%-
bind=,xf86audioraisevolume,exec,wpctl set-volume @DEFAULT_SINK@ 2%+
bind=,xf86audiomute,exec,wpctl set-mute @DEFAULT_SINK@ toggle
bind=CONTROL,xf86audiolowervolume,exec,playerctl previous
bind=CONTROL,xf86audioraisevolume,exec,playerctl next
bind=CONTROL,xf86audiomute,exec,playerctl play-pause
bind=,XF86monbrightnessup,exec,$HOME/.local/bin/backlightctl +1000
bind=,XF86monbrightnessdown,exec,$HOME/.local/bin/backlightctl -1000
bind=,XF86AudioPlay,exec,playerctl play-pause
bind=CONTROL,XF86AudioNext,exec,playerctl position 5+
bind=CONTROL,XF86AudioPrev,exec,playerctl position 5-
bind=,XF86AudioNext,exec,playerctl next
bind=,XF86AudioPrev,exec,playerctl previous
bind=,XF86AudioMicMute,exec,wpctl set-mute @DEFAULT_SOURCE@ toggle
bind=,XF86Display,exec,alacritty -e nvim $HOME/.config/hypr/hyprland.d/outputs.conf
bind=,XF86Favorites,exec,$HOME/.config/hypr/scripts/fan-speed.sh
bind=,XF86Keyboard,exec,alacritty --working-directory $HOME/.config/hypr/hyprland.d/ -e nvim general-keybinds.conf hyprland-keybinds.conf
bind=,XF86Tools,exec,alacritty --working-directory $HOME/.config -e nvim .
bind=,XF86Bluetooth,exec,notify-send "Bluetooth toggled"
bind=,XF86WLAN,exec,notify-send "WiFi toggled"
