bindm=SUPER,mouse:273,resizewindow
bindm=SUPER,mouse:272,movewindow

bind=SUPER,h,movefocus,l
bind=SUPER,j,movefocus,d
bind=SUPER,k,movefocus,u
bind=SUPER,l,movefocus,r

bind=SUPERSHIFT,h,movewindow,l
bind=SUPERSHIFT,j,movewindow,d
bind=SUPERSHIFT,k,movewindow,u
bind=SUPERSHIFT,l,movewindow,r
#
# bind=SUPERSHIFT,h, resizeactive, -10 0
# bind=SUPERSHIFT,j, resizeactive, 0 10
# bind=SUPERSHIFT,k, resizeactive, 0 -10
# bind=SUPERSHIFT,l, resizeactive, 10 0
#
bind=SUPERALT,h, resizeactive, -30 0
bind=SUPERALT,j, resizeactive, 0 30
bind=SUPERALT,k, resizeactive, 0 -30
bind=SUPERALT,l, resizeactive, 30 0

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10
bind=ALT,1,workspace,11
bind=ALT,2,workspace,12
bind=ALT,3,workspace,13
bind=ALT,4,workspace,14
bind=ALT,5,workspace,15
bind=ALT,6,workspace,16
bind=ALT,7,workspace,17
bind=ALT,8,workspace,18
bind=ALT,9,workspace,19
bind=ALT,0,workspace,20

bind=SUPERSHIFT,1,movetoworkspacesilent,1
bind=SUPERSHIFT,2,movetoworkspacesilent,2
bind=SUPERSHIFT,3,movetoworkspacesilent,3
bind=SUPERSHIFT,4,movetoworkspacesilent,4
bind=SUPERSHIFT,5,movetoworkspacesilent,5
bind=SUPERSHIFT,6,movetoworkspacesilent,6
bind=SUPERSHIFT,7,movetoworkspacesilent,7
bind=SUPERSHIFT,8,movetoworkspacesilent,8
bind=SUPERSHIFT,9,movetoworkspacesilent,9
bind=SUPERSHIFT,0,movetoworkspacesilent,10
bind=ALTSHIFT,1,movetoworkspacesilent,11
bind=ALTSHIFT,2,movetoworkspacesilent,12
bind=ALTSHIFT,3,movetoworkspacesilent,13
bind=ALTSHIFT,4,movetoworkspacesilent,14
bind=ALTSHIFT,5,movetoworkspacesilent,15
bind=ALTSHIFT,6,movetoworkspacesilent,16
bind=ALTSHIFT,7,movetoworkspacesilent,17
bind=ALTSHIFT,8,movetoworkspacesilent,18
bind=ALTSHIFT,9,movetoworkspacesilent,19
bind=ALTSHIFT,0,movetoworkspacesilent,20

bind=SUPER,W,togglegroup,
bind=SUPERSHIFT,W,moveoutofgroup,
bind=SUPER,Prior,changegroupactive,b
bind=SUPER,Next,changegroupactive,f
bind=SUPER,TAB,changegroupactive,f
bind=SUPERSHIFT,TAB,changegroupactive,b
bind=SUPERSHIFT,Q,killactive,
bind=SUPERSHIFT,space,togglefloating,
bind=SUPERALTSHIFT,L,exit,
bind=SUPER,P,pseudo,
bind=SUPER,M,fullscreen 
bind=SUPER,X,togglespecialworkspace

bind=SUPER,Backspace,exec,hyprlock
bind=SUPER,Delete,exec,hyprctl kill

# Cursor submap (similar to the Mouse mode in Sway)
# submap=cursor

# Jump cursor to a position
bind=SUPER,a,exec,wl-kbptr -o modes=floating,click -o mode_floating.source=detect

# Cursor movement
# binde=,j,exec,wlrctl pointer move 0 10
# binde=,k,exec,wlrctl pointer move 0 -10
# binde=,l,exec,wlrctl pointer move 10 0
# binde=,h,exec,wlrctl pointer move -10 0

# # Left button
# bind=,s,exec,wlrctl pointer click left
# # Middle button
# bind=,d,exec,wlrctl pointer click middle
# # Right button
# bind=,f,exec,wlrctl pointer click right

# Scroll up and down
bind=CONTROLSUPER,j,exec,wlrctl pointer scroll 10 0
bind=CONTROLSUPER,k,exec,wlrctl pointer scroll -10 0

# Scroll left and right
# bind=SUPER,h,exec,wlrctl pointer scroll 0 -10
# bind=SUPER,l,exec,wlrctl pointer scroll 0 10

# Exit cursor submap
# If you do not use cursor timeout or cursor:hide_on_key_press, you can delete its respective cals
# bind=,escape,exec,hyprctl keyword cursor:inactive_timeout 3; hyprctl keyword cursor:hide_on_key_press true; hyprctl dispatch submap reset 

# submap = reset

# Entrypoint
# If you do not use cursor timeout or cursor:hide_on_key_press, you can delete its respective cals
# bind=SUPER,g,exec,hyprctl keyword cursor:inactive_timeout 0; hyprctl keyword cursor:hide_on_key_press false; hyprctl dispatch submap cursor
