general {
    border_size=0
    gaps_in=2
    gaps_out=5,5,5,1
    
    # apply_sens_to_raw=0
    # sensitivity=0.50
    # main_mod=SUPER
}

decoration {

    # Inactive tile configs
    # Dimming
    dim_inactive=true
    dim_strength=0.1

    inactive_opacity=0.85
    
    # Prettify
    rounding=22
    blur {
        enabled=true
        size=2
        passes=2
        new_optimizations = true
    }

    shadow {
        enabled=true
        range=10
        render_power=4
        color=0x441a1a1a
      }
}

animations {
    bezier=easeinout,0.75, 1, 0.25, 1
    bezier=jumpinout,1,0,0,1
    enabled=1
    animation=windows,1,5,easeinout,slide
    animation=workspaces,1,5,jumpinout,slide
}

group {
  groupbar {
     gradients=false
     font_size=9
     text_color=0xff22191B
     col.inactive=0xffF3DDE0
     col.active=0xff8E4958
    }
  }

misc {
    font_family=SpaceMono Nerd Font
    splash_font_family=SpaceMono Nerd Font
  }
