dwindle {
    pseudotile=0
}

# Window rules
windowrule=float,class:^(gcolor3)$
windowrule=float,class:^(org.kde.kdeconnect)$
windowrulev2=nofocus,title:^(.*)(ibus)(.*)$
windowrulev2=noinitialfocus,title:^(.*)(ibus)(.*)$
windowrulev2=float,title:^(.*)(ibus)(.*)$
windowrulev2=opaque,title:^(.*)(ibus)(.*)$
windowrulev2=size 100 100,title:^(.*)(ibus)(.*)$
windowrule=float,class:^(ibus-extension-gtk3)$,title:^(ibus-extension-gtk3)$
# windowrule=float,class:^(firefoxdeveloperedition)$,initialTitle:Firefox
windowrule=float,class:^(java)$,title:^(Dbeaver)$
windowrule=float,class:^(thunar)$,title:^(File Operation Progress)$
windowrule=float,class:^(thunar)$,title:^(Confirm to replace files)$
windowrule=float,class:^(org.kde.dolphin)$,title:^(Copying)(.*)$
windowrule=float,class:^(QjackCtl)$,title:^(JACK Audio Connection Kit)(.*)$

# Firefox
windowrulev2=float,title:^(Picture-in-Picture)$
windowrulev2=pin,title:^(Picture-in-Picture)$
windowrulev2=size <500 <500,title:^(Picture-in-Picture)$
windowrulev2=keepaspectratio,title:^(Picture-in-Picture)$
windowrulev2=move onscreen 100% 100%,title:^(Picture-in-Picture)$
windowrulev2=nodim,title:^(Picture-in-Picture)$
windowrulev2=opaque,title:^(Picture-in-Picture)$

# Chromium
# windowrulev2=float,title:^(Picture-in-picture)$
# windowrulev2=pin,title:^(Picture-in-picture)$
# windowrulev2=move onscreen 100% 100%,title:^(Picture-in-picture)$

# scrcpy OTG Mode
windowrulev2=float,title:^(Redmi 14C)$
windowrulev2=pin,title:^(Redmi 14C)$
windowrulev2=move 99.85% -10%,title:^(Redmi 14C)$
windowrulev2=size 20% 120%,title:^(Redmi 14C)$

# Waydroid
windowrulev2=workspace special,class:^(waydroid)(.*)$
windowrulev2=float,class:^(waydroid)(.*)$
windowrulev2=xray,class:^(waydroid)(.*)$
windowrulev2=noblur,class:^(waydroid)(.*)$
windowrulev2=noshadow,class:^(waydroid)(.*)$
windowrulev2=noborder,class:^(waydroid)(.*)$

# Show Me The Key
windowrulev2=float,title:^(Floating Window - Show Me The Key)$
windowrulev2=nofocus,title:^(Floating Window - Show Me The Key)$
windowrulev2=size 100% 70px,title:^(Floating Window - Show Me The Key)$
windowrulev2=move 0% 0%,title:^(Floating Window - Show Me The Key)$

windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrule = noanim, class:^(xwaylandvideobridge)$
windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrule = noblur, class:^(xwaylandvideobridge)$
windowrule = nofocus, class:^(xwaylandvideobridge)$
